name: CI
on:
    push:
        branches:
            - main
jobs:
    docs:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [10.x, 12.x, 14.x]
                # Temporarily removed 15.x
        steps:
            - uses: actions/checkout@v2.3.1

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Run tests
              run: |
                  npm install -D
                  npm run test
