name: Documentation

on:
    push:
        branches:
            - main
        paths:
            - src/**
            - README.md
jobs:
    docs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              node-version: 20.x
              cache: npm

            - name: 🚧 Install dependencies
              run: npm install

            - name: 👷 Build site
              run: npm run docs

            - name: 🚀 Deploy
              uses: zyrouge/gh-push-action@v1
              with:
                  branch: gh-pages
                  directory: docs-dist
