name: Documentation

on:
    push:
        branches:
            - main
        paths:
            - src/**
            - README.md
jobs:
    docs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2.3.1

            - name: 🚧 Install dependencies
              run: npm install

            - name: 👷 Build site
              run: npm run docs

            - name: Deploy 🚀
              uses: zyrouge/gh-push-action@v1.0.5
              with:
                  branch: gh-pages
                  directory: docs-dist
